### PR TITLE
Median filter wrapper

### LINKED ISSUE #371: Adding 'median' function
This is a continuation of what was discussed in issue #370.

I'm going to try to recreate the IRAF task 'median'. I imagine it as essentially being a wrapper to the scipy medfilt2 function.

I'm new to contributing so any suggestions about how best to proceed are welcome!

### PR DESCRIPTION
**Pull request by MSeifert04**
Please have a look at the following list and replace the "[ ]" with a "[x]" if
the answer to this question is yes.

- [ ] For new contributors: Did you add yourself to the "Authors.rst" file?

For documentation changes:

- [ ] For documentation changes: Does your commit message include a "[skip ci]"?
      Note that it should not if you changed any examples!

For bugfixes:

- [ ] Did you add an entry to the "Changes.rst" file?
- [ ] Did you add a regression test?
- [ ] Does the commit message include a "Fixes #issue_number" (replace "issue_number").
- [ ] Does this PR add, rename, move or remove any existing functions or parameters?

For new functionality:

- [x] Did you add an entry to the "Changes.rst" file?
- [ ] Did you include a meaningful docstring with Parameters, Returns and Examples?
- [x] Does the commit message include a "Fixes #issue_number" (replace "issue_number"): Fixes #371
- [x] Did you include tests for the new functionality?
- [ ] Does this PR add, rename, move or remove any existing functions or parameters?

Please note that the last point is not a requirement. It is meant as a check if
the pull request potentially breaks backwards-compatibility.

-----------------------------------------

### CODE REVIEW

**Comment by MSeifert04** [comment]
This is the simple wrapper alternative for #415. Please do not close the other PR if this is merged. I rather hope an extended `support_nddata` wrapper would make sense for several functions (including `block_reduce`, ...).

**Comment by mwcraig** [comment]
Thanks, feel free to merge when the lights turn green.

**Comment by MSeifert04** [comment]
I've added a new section to the reduction toolbox (that was what you meant, right?):

unbenannt

**Comment by MSeifert04** [comment]
@mwcraig You're fast. 😄

**Comment by mwcraig** [comment]
Thanks, merging.

**Comment by MSeifert04** [comment]
Thanks!

**Pull request merged**
