### PR TITLE
Use CCDData from astropy.nddata if astropy version >= 2.0

### LINKED ISSUE #510: use astropy.nddata.CCDData
For the next release, we should make sure to include the new astropy.nddata.CCDData to be used for ccdproc.CCDData

### PR DESCRIPTION
**Pull request by MSeifert04**
Fixes #510  (and maybe #232)

I tried to make minimal changes but a few tests had to be rewritten and the logging system now works a bit differently.

I included some comments about the need for the change but if some change seems "weird" please mention it so I can include a comment why that's needed.

### CODE REVIEW

**Comment by MSeifert04** [comment]
It probably makes more sense to review the commits individually. The first one makes the code changes while the second one (tries) to fix the sphinx problems.

**Comment by mwcraig** [comment]
I'll review this over the weekend.

**Comment by MSeifert04** [comment]
@mwcraig Did you have time to review the PR?

**Comment by MSeifert04** [comment]
@mwcraig Thank you for the review. 👍 I'll keep this open until tomorrow in case @crawfordsm wants to take a look as well.

**Pull request merged**
