### PR TITLE
add scikit-image to rtd-requirements

### PR DESCRIPTION
**Pull request by MSeifert04**
I don't know if that would fix the failing readthedocs builds (http://readthedocs.org/projects/ccdproc/builds/) but I did forget to add it there.

### CODE REVIEW

**Comment by mwcraig** [comment]
Merging even though CI isn't done yet...

**Comment by mwcraig** [comment]
Not sure it will build all the way, but it is getting farther in the build than it was...

**Comment by MSeifert04** [comment]
I just checked and it passed. The block_x functions are also present: http://ccdproc.readthedocs.io/en/latest/ccdproc/index.html#module-ccdproc

**Comment by MSeifert04** [comment]
@mwcraig Thanks for merging!

**Pull request merged**
