### PR TITLE
Issue #235. Removed discussion of Keyword class in Getting Started section.

### PR DESCRIPTION
**Pull request by Punyaslok**
Removed discussion of Keyword class in Getting Started section of documentation (index.rst).

### CODE REVIEW

**Comment by Punyaslok** [comment]
Hi, I'm a newbie to the world of Open Source. If any changes need to be made, please suggest them to me.

I've removed the discussion about the Keyword class. The class seems to be irrelevant and unused in ccdproc and even Keyword's own documentation does not fully explain its usage(http://ccdproc.readthedocs.org/en/latest/api/ccdproc.Keyword.html#ccdproc.Keyword).

**Comment by bsipocz** [comment]
@Punyaslok - Thanks for the contribution. The rst files are also tested, but the current failures are due to different reasons:

- build #6 fail is totally unrelated and due to the fact the coveralls servers seems to be down, and the report cannot be uploaded. You can ignore this for now.
- The builds against the development version of astropy are failing due to another unrelated reason, and it's worked on in #292 and related PRs. You can ignore this one for now, too.

**Comment by Punyaslok** [comment]
@bsipocz 
So, what do I do now? Will the pull request be automatically be re-checked after 292 gets resolved or do I have to submit another pull request afterwards?
Also as I am new, can you suggest me some issues that will help me get started?
Thanks.

**Comment by bsipocz** [comment]
@Punyaslok - One point of start is to read the development guide of Astropy, the same guidelines apply for ccdproc, too. http://docs.astropy.org/en/latest/development/workflow/development_workflow.html

Ideally you should never open a duplicate PR for the same issue. The fails here will be resolved when those bug fixes are merged. Then a maintainer can restart the travis builds, and in the worst case will ask you to rebase your branch.

**Comment by mwcraig** [comment]
@bsipocz -- thanks for tracking down the errors.

@Punyaslok -- thanks for the contribution! I'll restart the failing tests once we're sure the underlying problems (all unrelated to your pull request) have been fixed. No need to open a separate pull request.

**Pull request merged**
