### PR TITLE
Do not gain correct data when identifying cosmic rays

### PR DESCRIPTION
**Pull request by mwcraig**
Not sure this is the best fix, but it will get the job done.

### CODE REVIEW

**Comment by MSeifert04** [comment]
Do we really want to change the output of a function so drastically in a bug-fix release?

Couldn't we add an "apply_gain" parameter to the function which defaults to True (previous behavior) which can be set to False if the uncorrected image is needed (with your patch)? That way we don't break any code that uses this function and we could (gradually) change the default in the future?

**Comment by MSeifert04** [comment]
Otherwise the change/test look great. Thanks for tackling this Matt.

**Comment by mwcraig** [comment]
> Do we really want to change the output of a function so drastically in a bug-fix release?

I guess it depends on whether we think it is a bug (in which case a bug fix makes sense) or an undocumented feature (in which case we'd be breaking the API).

I'll discuss with @crawfordsm today.

**Comment by mwcraig** [comment]
A couple of comments while I’m thinking about them:

+ There is a unit issue in the current behavior — as pointed out in #705, the gain is applied but the units of the data are not updated. 
+ The gain cannot have have units in our current implementation because astroscrappy doesn’t handle them. We could handle units in our wrapper. 

I’m increasingly leaning towards a feature release to fix these things because the current API has issues.

**Comment by MSeifert04** [comment]
> I’m increasingly leaning towards a feature release to fix these things because the current API has issues.

I like that idea. 

However there are some additional issues:

- How do we handle gain if an array is passed in instead of a `CCDData`.
- Do we make gain-correction a documented feature of the function, or an optional feature, or do we remove it completely?
- How do we handle units? Normally plain data is in units of ADU and gain is in e-/ADU (or ADU/e-). However what do we do if one of these assumptions is wrong?

**Comment by mwcraig** [comment]
@crawfordsm and I talked about this extensively a little while ago. I'm going to close this and open a different PR shortly that outlines a more complete approach.

**Pull request closed without merging**
