### PR TITLE
Adapt for NumPy dev representation changes

### PR DESCRIPTION
**Pull request by MSeifert04**
Fixes the failing NumPy dev doctests

### CODE REVIEW

**Comment by mwcraig** [comment]
Hmmm, looks like tests fail now after merging. Is it possible that numpy changed the repr again?

**Comment by MSeifert04** [comment]
> Is it possible that numpy changed the repr again?

That's possible. 

Do you have a link to a new failed build?

**Comment by mwcraig** [comment]
Sorry for the noise, the fail was for a build *before* I merged this.

**Comment by MSeifert04** [comment]
okay, thanks for confirming it. I was looking through the logs and couldn't find the failure.

**Pull request merged**
