### PR TITLE
Adding python 3.6 to CI builds

### PR DESCRIPTION
**Pull request by bsipocz**
Probably we need to wait a bit more until all the dependencies become available on python 3.6.

### CODE REVIEW

**Comment by MSeifert04** [comment]
Some small comments:

- could you include an egg-test for 3.6
- also a test for python 3.5 + np.1.11
- and make the numpy prerelease-test use python 3.6

Otherwise lots of green marks 👍 Seems like we are 3.6 compatible :)

**Comment by bsipocz** [comment]
@MSeifert04 - Done. np1.11 was "stable" when this PR was opened :)

**Comment by MSeifert04** [comment]
@bsipocz Thanks! 👍 

I restarted the failed tests because "only" something went wrong during the `coveralls`-command.

**Comment by MSeifert04** [comment]
I'm going ahead an merge this. Long overdue :)

Thanks @bsipocz

**Pull request merged**
