### PR TITLE
Enhance image collection.py

### PR DESCRIPTION
**Pull request by michaelwerger**
Allow search for keywords like OBS-TIME or EXP-TIME which are FITS compliant, examples:
print(collection.files_dictfiltered({'CCD-TEMP':'0.4'}))
or
print(collection.files_dictfiltered({'EXPTIME':'0.03', 'DATE-OBS':'27T14'}))

Please have a look at the following list and replace the "[ ]" with a "[x]" if
the answer to this question is yes.

- [x] For new contributors: Did you add yourself to the "Authors.rst" file?

For documentation changes:

- [ ] For documentation changes: Does your commit message include a "[skip ci]"?
      Note that it should not if you changed any examples!

For bugfixes:

- [ ] Did you add an entry to the "Changes.rst" file?
- [ ] Did you add a regression test?
- [ ] Does the commit message include a "Fixes #issue_number" (replace "issue_number").
- [ ] Does this PR add, rename, move or remove any existing functions or parameters?

For new functionality:

- [ ] Did you add an entry to the "Changes.rst" file?
- [x] Did you include a meaningful docstring with Parameters, Returns and Examples?
- [ ] Does the commit message include a "Fixes #issue_number" (replace "issue_number").
- [ ] Did you include tests for the new functionality?
- [ ] Does this PR add, rename, move or remove any existing functions or parameters?

Please note that the last point is not a requirement. It is meant as a check if
the pull request potentially breaks backwards-compatibility.

-----------------------------------------

### CODE REVIEW

**Comment by MSeifert04** [comment]
You can also pass in a dict to `files_filtered`:

```
collection.files_filtered(**{'EXPTIME':'0.03', 'DATE-OBS':'27T14'})
```

Won't that work

**Comment by michaelwerger** [comment]
No, sorry,:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-a05de9f15151> in <module>()
----> 1 print(collection.files_filtered(**{'EXPTIME':'0.03', 'DATE-OBS':'27T14'}))

/Users/Micha/Workspaces/ccdproc/ccdproc/image_collection.py in files_filtered(self, **kwd)
    432         Parameters
    433         ----------
--> 434         include_path : bool, keyword-only
    435             If the keyword ``include_path=True`` is set, the returned list
    436             contains not just the filename, but the full path to each file.

/Users/Micha/Workspaces/ccdproc/ccdproc/image_collection.py in _find_keywords_by_values(self, **kwd)
    785 
    786             matches &= have_this_value
--> 787 
    788         # the numpy convention is that the mask is True for values to
    789         # be omitted, hence use ~matches.

AttributeError: 'numpy.float64' object has no attribute 'lower'


That was the reason I want to improve ImageCollection…, 

Maybe I still missed something.
Nevertheless,
Cheers,
Michael Werger

Am 24.09.2017 um 21:13 schrieb Michael Seifert <notifications@github.com>:

collection.files_filtered(**{'EXPTIME':'0.03', 'DATE-OBS':'27T14'})

> Dr. Michael Werger
> Emdener Str. 31
> 45481 Mülheim an der Ruhr
> +171 1903804
> mwerger@t-online.de
> www.4w-online.de <http://www.4w-online.de/>

**Comment by MSeifert04** [comment]
The traceback seems unrelated. I can't see how the documentation can be responsible for the exception. 

And what versions (astropy, ccdproc, numpy) are you using?

**Comment by michaelwerger** [comment]
Numpy: 1.13.1
Astropy: 2.0.1
ccdproc: todays pull from master


Am 24.09.2017 um 21:20 schrieb Michael Seifert <notifications@github.com>:

The traceback seems unrelated. I can't see how the documentation can be responsible for the exception.

And what versions (astropy, ccdproc, numpy) are you using?

**Comment by MSeifert04** [comment]
Could you maybe add the version info plus a correct traceback as issue?

**Comment by michaelwerger** [comment]
sure, I’ll try:

Version of ccdproc: 1.3 (or is there a special way to read the version)?


Traceback (most recent call last):
  File "fits_processing.py", line 18, in <module>
    print(collection.files_filtered(**{'EXPTIME':'0.03', 'DATE-OBS':'27T14'}))
  File "/Users/Micha/Workspaces/ccdproc/ccdproc/image_collection.py", line 484, in files_filtered
    self._find_keywords_by_values(**kwd)
  File "/Users/Micha/Workspaces/ccdproc/ccdproc/image_collection.py", line 837, in _find_keywords_by_values
    value_matches = (file_key_value.lower() ==
AttributeError: 'numpy.float64' object has no attribute ‚lower'



Am 24.09.2017 um 21:39 schrieb Michael Seifert <notifications@github.com>:

Could you maybe add the version info plus a correct traceback as issue?

**Comment by MSeifert04** [comment]
Thank you. I'll have a look.

**Comment by MSeifert04** [comment]
Hi @michaelwerger 

The problem with the `.lower()` should be fixed in the next release (by #567) and we also added an example of how to pass a dictionary to the `files_filtered` method (in #580). These should fix the issues you were having so I'm closing the pull request. Feel free to re-open it (or open an issue) if you're still having problems after the next release (which should be available later today).

**Comment by michaelwerger** [comment]
Hi,
thank you for working on this! I removed my old local version, cloned the latest one from GitHub and run my script again. However, I’m still not sure how to read keywords like ´CCD-TEMP´in the following header:

SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                   16 / number of bits per data pixel                  
NAXIS   =                    2 / number of data axes                            
NAXIS1  =                 4944 / length of data axis 1                          
NAXIS2  =                 3284 / length of data axis 2                          
EXTEND  =                    T / FITS dataset may contain extensions            
COMMENT   FITS (Flexible Image Transport System) format is defined in ‚Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
BZERO   =                32768 / offset data range to that of unsigned short    
BSCALE  =                    1 / default scaling factor                         
OBSERVER= 'Michael '           / SBIGFITSEXT The name of the observer           
ORIGIN  = 'WHS     '           / Description of location                        
TELESCOP= 'TS 130/650'         / SBIGFITSEXT The model Telescope                
FOCALLEN=                 650. / SBIGFITSEXT Telescope focal length in mm       
APTAREA =              125100. / SBIGFITSEXT Aperture area mm^2 less central obs
APTDIA  =                 130. / SBIGFITSEXT Aperture diameter in mm            
SBUUID  = '{a5200a52-1f97-4423-a1fe-b0109ab1b793}' / Photo UUID                 
EXPTIME =                   1. / SBIGFITSEXT Total exposure time in seconds     
SWCREATE= 'TheSkyX Version 10.5.0 Build 10305' / SBIGFITSEXT Name & version of s
COLORCCD=                    0 / Non zero if image is from a color ccd          
DISPINCR=                    1 / Non zero to automatically display the image in 
PICTTYPE=                    1 / Image type as index 0= Unknown 1=Light, 2=Bias,
IMAGETYP= 'Light Frame'        / SBIGFITSEXT Light, Dark, Bias or Flat          
XORGSUBF=                    0 / SBIGFITSEXT Subframe x upper-left pixel in bin 
YORGSUBF=                    0 / SBIGFITSEXT Subframe y upper-left pixel in bin 
XBINNING=                    1 / SBIGFITSEXT Binning factor in width            
YBINNING=                    1 / SBIGFITSEXT Binning factor in height           
CCD-TEMP=                 11.2 / SBIGFITSEXT Temperature of the CCD             
INSTRUME= 'ASICamera'          / SBIGFITSEXT The model camera used.             
DATE-OBS= '2017-10-18T19:48:52.929' / SBIGFITSEXT UTC of start exp. in ISO 8601 
LOCALTIM= '18.10.17 21:48 DST' / The local time for display only (format dependsEND

If I tried the follwing

ic_all = ccdproc.ImageFileCollection(datapath,glob_include='*.fit', keywords='*')
matches = (ic_all.summary['CCD-TEMP'] == '11.2')
print(matches.summary['file'][matches] )

I got an error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-39-8cda3ecd97d6> in <module>()
      1 ic_all = ccdproc.ImageFileCollection(datapath,glob_include='*.fit', keywords='*')
----> 2 matches = (ic_all.summary['CCD-TEMP'] == '11.2')
      3 print(matches.summary['file'][matches] )

~/anaconda/envs/astropy2/lib/python3.6/site-packages/astropy/table/table.py in __getitem__(self, item)
   1222     def __getitem__(self, item):
   1223         if isinstance(item, six.string_types):
-> 1224             return self.columns[item]
   1225         elif isinstance(item, (int, np.integer)):
   1226             return self.Row(self, item)

~/anaconda/envs/astropy2/lib/python3.6/site-packages/astropy/table/table.py in __getitem__(self, item)
    107         """
    108         if isinstance(item, six.string_types):
--> 109             return OrderedDict.__getitem__(self, item)
    110         elif isinstance(item, (int, np.integer)):
    111             return self.values()[item]

KeyError: 'CCD-TEMP'

I’m using Anaconda 3, Python 3.6

Do I something wrong? Any Idea? 

Cheers,

Michael Werger


Am 01.11.2017 um 19:47 schrieb Michael Seifert <notifications@github.com>:

Closed #557 <https://github.com/astropy/ccdproc/pull/557>.

**Comment by MSeifert04** [comment]
The problem is that the 11.2 is a number not a string, so you have to compare it using `ic_all.summary['CCD-TEMP'] == 11.2`.

**Pull request closed without merging**
