### PR TITLE
Added changelog for glob* parameters in ImageFileCollection

### LINKED ISSUE #487: reminder to add changes.rst
Add #484  and adrn to change log and authors list.

### PR DESCRIPTION
**Pull request by MSeifert04**
and refactored some of the internals

Fixes #487

### CODE REVIEW

**Comment by MSeifert04** [comment]
This also adresses two comments I had in the original PR #484.

**Comment by mwcraig** [comment]
LGTM, pretty straightforward, so merging.

**Comment by mwcraig** [comment]
Reminder to @MSeifert04, @crawfordsm and @mwcraig: set milestone before or just after merging. 😀

**Comment by bsipocz** [comment]
@mwcraig - @astrobot could help you remember it, if you want :)

**Comment by MSeifert04** [comment]
that sounds like an interesting idea. 

Well, ... he's a bit arrogant but if *it* could help why not? 😄

Should we open a discussion/question issue, so we don't forget about it?

**Comment by bsipocz** [comment]
You say arrogant, I say confident, as a robot should be 😉

**Comment by mwcraig** [comment]
Issue opened! Welcome the new 🤖 ruler!

**Pull request merged**
