### PR TITLE
Add replace_ argument for files_filtered and _generator

### PR DESCRIPTION
**Pull request by MSeifert04**
- [x] Did you add an entry to the "Changes.rst" file?
- [x] Did you include a meaningful docstring with Parameters, Returns and Examples?
- [x] Does the commit message include a "Fixes #issue_number" (replace "issue_number").
- [x] Did you include tests for the new functionality?
- [x] Does this PR add, rename, move or remove any existing functions or parameters?

Fixes: #481 

CC: @bsipocz

### CODE REVIEW

**Comment by MSeifert04** [comment]
I'm not sure if it's good style to have an argument that starts with an underscore, I just wanted to avoid unnecessary conflicts with valid argument names and it distinguishes it from regular filtering argument names. But it could also be considered private (Python convention) which wouldn't be good.

**Comment by MSeifert04** [comment]
Possible alternatives:

- instead of making this an argument it could also be an instance attribute.
- other argument name, not starting with an underscore, but that *could* conflict with existing header keywords.

**Comment by MSeifert04** [comment]
I have thought about the alternatives some more and I would like to keep it an argument and I don't think it would be a problem with the leading underscore. However I would prefer a shorter name, e.g. `_repl` or `_replace` or such like.

**Comment by bsipocz** [comment]
Thanks @MSeifert04 for picking this up. 
I have to admit that I I won't have time in the coming weeks to go back to that piece of work that triggered this feature, but this definitely seems to be an improvement.

**Comment by mwcraig** [comment]
I think `replace_with_whitespace` would work as a keyword without a leading underscore (it seems unlikely to be a keyword). If we want to underscore it, could we go with `replace_with_whitespace_`?

This is good to go otherwise...

**Comment by MSeifert04** [comment]
Yes, it shouldn't create conflicts, I don't think there are many files with a `replace_with_whitespace` header card around. But also the length of the argument is a bit annoying but the shorter it gets the more likely there will be collisions.

**Comment by mwcraig** [comment]
What about going with `replace_`?

**Comment by MSeifert04** [comment]
I really like `replace_` and changed the argument name. :)

**Pull request merged**
