### PR TITLE
Fix calculation of `ystep` in `combine`

### PR DESCRIPTION
**Pull request by mwcraig**
The first commit here adds a regression test; I haven't pushed the fix yet so I expect it to fail.

I moved calculation of the steps into a function of its own because it made testing much simpler.

### CODE REVIEW

**Comment by mwcraig** [comment]
This is ready for a look, assuming tests pass

**Comment by MSeifert04** [comment]
It could make sense to **only** slice along the non-contiguous dimension to only get contigous "chunks". That would avoid memory fragmentation and (somewhat) unnecessary mmap-calls (at least if memory-mapping is used). That would also simplify the logic because we only need to check which axis should be sliced and how often, that way it would be (relatively) easy to also support ND images, not just 2D. I guess the case where slicing along one axis in 1-steps (the lower limit) would exceed the memory limit is probably very rare?!

**Comment by mwcraig** [comment]
I'm guessing the cases where slicing along more than 1 axis needs to happen are exceedingly rare (unless you do all of your data reduction on a raspberry pi or some maybe?).

it is tempting to have numpy reshape the data into a 1d array always; then the chunking is very similar. The result could be built up as a 1d array then reshaped to the correct shape at the end.

I ran out of time/enthusiasm though....

**Comment by MSeifert04** [comment]
> I ran out of time/enthusiasm though....

If you want - I can give it a try. :)

**Comment by mwcraig** [comment]
Feel free!

**Comment by crawfordsm** [comment]
Let's merge as is -- we can revisit this as part of the combine re-factor later if needed.

**Pull request merged**
