### PR TITLE
Use full path in ccd generator (replaces #422)

### PR DESCRIPTION
**Pull request by mwcraig**
This is another rebase of #422 and contains the changes originally in (and discussed at) that PR.

### CODE REVIEW

**Comment by MSeifert04** [comment]
This definitly needs a regression test but we can also add that later (maybe an effort-easy issue?).

**Comment by mwcraig** [comment]
I'll add a regression test tonight, might as well do it while it is fresh in my mind.

**Review by MSeifert04 — APPROVED** [review]
LGTM, thanks for adding the regression test.

Removing the empty line in the changelog is probably asking for a merge conflict but the other open PRs are all mine so it shouldn't be a problem :-)

**Comment by mwcraig** [comment]
I'll revert that change (won't bother squashing) then this can be merged once coveralls is done (will skip CI on the un-removal of the blank line :)).

**Pull request merged**
