### PR TITLE
Enable doctests

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by mwcraig** [comment]
@bsipocz -- thanks! Could you please add `matplotlib` to the dependencies installed in `.travis.yml`? Looks like the fails occur when a doctest tries to install `matplotlib `.

**Comment by bsipocz** [comment]
Sure. Is ``matplotlib`` an optional dependency, isn't it?

**Comment by mwcraig** [comment]
Yes, it is optional.

**Comment by bsipocz** [comment]
Done. It seems that matplotlib isn't used anywhere in the code, and I should have skipped that test anyway.

**Comment by mwcraig** [comment]
Looks good, thanks again for getting this working!

**Comment by bsipocz** [comment]
No problem, I guess ccdproc was my side-track sprint for today :)

**Pull request merged**
