### PR TITLE
Adding appveyor testing and opting in ci-helpers

### LINKED ISSUE #259: Add testing on appveyor

### PR DESCRIPTION
**Pull request by bsipocz**
This is to address and close #259.

I've also added ccdproc as a project on appveyor itself for astropy.

### CODE REVIEW

**Comment by hamogu** [comment]
The Travis test fails, because the pytest plugin pytest-capture log is not installed. Before your PR, that was done manually in `.travis.yml`, now you rely on `pytest_requires` in setup.py, which does not work.
See: https://github.com/astropy/astropy-helpers/issues/212

Either pip pytest-capture log need to be called by hand (in .travis.yml) or we need to add this package to `install_requires` (although technically it's not required for the installation, just to run the tests).

Note that I have a strong interest to make this PR work, too, because my own PRs #274 and #275 now have failing tests because the appveyor setup is not complete. ;-)

**Comment by bsipocz** [comment]
@hamogu - Sure, I'll make this work in the weekend. It's seems to be trivial to fix, I just didn't have any time today to iron it out (last night the builds were piling up and it was hopeless to wait for them to finish).

**Comment by crawfordsm** [comment]
Thanks for submitting it @bsipocz and let me know if you need anything from us. 

Thanks  @hamogu for reviewing it.  Once the tests are back up and running we will restart the outstanding pull requests.

**Comment by mwcraig** [comment]
@bsipocz -- I'll try to fix the Windows errors (may need to rewrite tests or mark some as skip on Windows ) if you want to take care of the travis fail...if you want to do Windows too, let me know, I won't stand in the way :)

**Comment by bsipocz** [comment]
Travis is basically fixed, the astropy version number is case sensitive, but I already have the PR in ci-helpers to make it insensitive.

The windows failures are a different case, they look genuine and I don't have much windows experience since win98, so can only try and hack around with the help of our mutual friend, google. 
What about xfailing them in this PR and opening an issue for it, so you or whoever gets there first can fix it when have extra time?

**Comment by mwcraig** [comment]
xfailing sounds good. I've looked into the underlying issue before, it has to do with (at least in some of the cases) with overwriting files in Windows. Though the fail happens in io.fits, it is something in `ImageFileCollection`, I think, that is keeping a reference to a file that makes Windows unhappy.

**Comment by mwcraig** [comment]
Do you want me to do the xfails?

**Comment by bsipocz** [comment]
Nope, I already started it. Just waiting for the ci-helpers fix before pushing the commit.

**Comment by bsipocz** [comment]
@hamogu - the tests in your PRs will be also marked xfail on Appveyor until #276 is fixed, as they are within the marked class.  They would most probably fail anyway as @mwcraig said above the problem lies somewhere in ``ImageFileCollection``.

**Comment by bsipocz** [comment]
@mwcraig - This doesn't need a changelog entry, right? Or should the windows testing be mentioned somewhere?

**Comment by mwcraig** [comment]
@bsipocz -- thanks for all of your work on this!

@hamogu -- can you please rebase #274 and #275 after I merge?

**Comment by mwcraig** [comment]
@bsipocz  -- nope, no need for changelog.

**Pull request merged**
