### PR TITLE
Add Shutter Correction Functionality (take two)

### PR DESCRIPTION
**Pull request by joshwalawender**
For new functionality:

- [x] Did you add an entry to the "Changes.rst" file?
- [x] Did you include a meaningful docstring with Parameters, Returns and Examples?
- [ ] Does the commit message include a "Fixes #issue_number" (replace "issue_number").
- [x] Did you include tests for the new functionality?
- [ ] Does this PR add, rename, move or remove any existing functions or parameters?

Please note that the last point is not a requirement. It is meant as a check if
the pull request potentially breaks backwards-compatibility.

-----------------------------------------

Hi all, this is attempt two at a PR for this functionality (see PR #419).  The git history on that one got fouled up.  I hope this version works.  I ran the tests on my system (they passed), but haven't done a complete examination.

### CODE REVIEW

**Comment by bsipocz** [comment]
@joshwalawender - I'm afraid this PR is even more contaminated with unrelated commits than the other one. If you want I can walk you through a rebase/fix for either of them (preferably the previous one) on gitter some time tomorrow.

**Comment by joshwalawender** [comment]
Sorry for the continued troubles.  Would it be easiest if I just generated a fresh branch from the latest master than just paste in the two new files and create a PR for that branch?  That would lose the commit history, but (hopefully) cleanup these problems.  I'm happy to handle it via rebase too if that is better, but I'd obviously need help.

**Comment by mwcraig** [comment]
@joshwalawender -- please go ahead and try with a fresh branch. Sometimes that is the easiest way to go, by far.

**Comment by mwcraig** [comment]
@joshwalawender -- are you still interested in moving this forward?

**Comment by joshwalawender** [comment]
@mwcraig I have good intentions, but at this point, if I get to it, I'd probably just create a new PR rather than try to drag this one forward through all the changes to cupric since then.

**Pull request closed without merging**
