### PR TITLE
Reduce test warnings

### PR DESCRIPTION
**Pull request by Yash-10**
Addressed some test warnings that come up while testing. Also made comments consistent along the way.

Thanks!

### CODE REVIEW

**Comment by Yash-10** [comment]
@mwcraig, could you please review this PR?

Thanks!

**Comment by Yash-10** [comment]
For the windows CI test, it seems that `len(recwarn)` is 2 and hence the assertion fails. Although these tests on macos and ubuntu are cancelled. [This](https://github.com/astropy/ccdproc/blob/master/ccdproc/tests/test_cosmicray.py#L128) line renders a log message
```
array provided for uncertainty; assuming it is a StdDevUncertainty. [astropy.nddata.ccddata]
```
so probably this is been captured by `recwarn` in some way?

**Comment by mwcraig** [comment]
It looks like that call is now generating two warnings because of a new deprecation warning from numpy. I think dropping the check for the number of warnings would work for now.

**Comment by Yash-10** [comment]
Hello @mwcraig, thank you for your reply. One of the deprecation warnings has been fixed here and the other seems to be coming from `astroscrappy`, the equivalent fix of which was already done and is close to be merged. Also, as you had suggested, the check for the number of warnings is dropped now.

Thank you.

**Comment by mwcraig** [comment]
Excellent, thanks! I'll try to get 2.1.1 released today.

**Pull request merged**
