### PR TITLE
Copy Meta in ccd_process when "subtract_bias" image

### LINKED ISSUE #401: ccd_process does not keep header
When ccd_process processes a file, the return object appears to lose its header information.

### PR DESCRIPTION
**Pull request by MSeifert04**
I identified one place where the `meta` could be lost when calling `ccd_process` (#401).

Maybe @crawfordsm or @RogueAstro could confirm if this PR fixes the issue.

Closes #401

### CODE REVIEW

**Comment by RogueAstro** [comment]
This PR fixed the issue on my end.

**Comment by mwcraig** [comment]
@MSeifert04 -- wow, the github graphics when you request a change are really harsh!

**Comment by MSeifert04** [comment]
@mwcraig No problem. I added the test.

**Comment by crawfordsm** [comment]
Thanks @MSeifert04 !

**Pull request merged**
