### PR TITLE
Removed 1.1.1 section of the changelog.

### PR DESCRIPTION
**Pull request by MSeifert04**
There won't be a 1.1.1 release (I think) so I've moved those entries to 1.2.0

### CODE REVIEW

**Comment by mwcraig** [comment]
Could you please switch `scikit-image` back to a required dependency? it seems like it should be easy for people to install (or at least `scipy` and `numpy` are much harder to compile from source, and anaconda offers packages for scikit-image in its defaults channel).

**Comment by mwcraig** [comment]
As an alternative, add: `setup_requires=['scikit-image']`

**Comment by MSeifert04** [comment]
@mwcraig I've rebased the PR but skipped the CI (conflict was just in Changes.rst).

**Comment by mwcraig** [comment]
Having looked into `extra_requires` a bit more I'm leaning back towards just making `scikit-image` a hard requirement. The rationale is that once we add an `extras_require`, the advice from the [setuptools documentation](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) is to keep the extra requirement around forever (well, to be more specific, `extra_requires` is a dictionary, and the *key* should stay around forever).

Also, the [semantic version docs](http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api) seem to indicate that adding a requirement does not count as a backwards-compatibility-breaking change (assuming the accompanying API change is backwards compatible). 

If this were a patch release it might be different, but for a minor version bump adding a requirement seems fine. If we don't, then we need to update the documentation to indicate that a couple of functions require `scikit-image` and/or change the recommended install command to `pip install ccdproc[all]`.

**Comment by bsipocz** [comment]
(If ``scikit-image`` is an optional dependency, not only the documentation should acknowledge it, but  tests, too. If it's not a hard dependency then tests should always respect that and pass with or without it, and that may turn out to be an unnecessary maintenance overhead.)

**Comment by MSeifert04** [comment]
> Also, the semantic version docs seem to indicate that adding a requirement does not count as a backwards-compatibility-breaking change (assuming the accompanying API change is backwards compatible). 

In that case I think it would be best to put it in the `install_requires` section again. 

@mwcraig Do you want to change it? Also the `_optional_` should be removed from the `Changes.rst` as well.

**Comment by MSeifert04** [comment]
I've removed the removal of `scikit-image` in `install_requires` and removed the word `optional` in the changelog again.

**Comment by mwcraig** [comment]
Thanks, merging!

**Pull request merged**
