### PR TITLE
Remove several properties already present in NDDataArray

### PR DESCRIPTION
**Pull request by mwcraig**
This PR removes several properties that are already defined in `NDDataArray`. The only one that differed in any way from `NDDataArray` is `unit`. It's setter in `NDDataArray` is at https://github.com/astropy/astropy/blob/master/astropy/nddata/compat.py#L146

I'm going to hold off on opening the PR to astropy until this is merged.

### CODE REVIEW

**Comment by mwcraig** [comment]
@crawfordsm @MSeifert04 -- I'm planning to merge this soon unless there are objections. I want to get this in before I open up the the PR on astropy core. This PR just removes some properties that are also in `NDDataArray` in astropy core.

**Comment by MSeifert04** [comment]
I'm not sure about the `unit`. That would allow setting the `unit` to `None` (effectivly a `CCDData` without unit). The other attributes are fine.

**Comment by mwcraig** [comment]
Ah, right, thanks for catching that. I'll revert that part of it.

**Comment by mwcraig** [comment]
Also added a regression test for the unit setter...

**Review by MSeifert04 — APPROVED** [review]
LGTM

**Pull request merged**
