### PR TITLE
[No-MERGE] modified "support_nddata" decorator.

### LINKED ISSUE #371: Adding 'median' function
This is a continuation of what was discussed in issue #370.

I'm going to try to recreate the IRAF task 'median'. I imagine it as essentially being a wrapper to the scipy medfilt2 function.

I'm new to contributing so any suggestions about how best to proceed are welcome!

### PR DESCRIPTION
**Pull request by MSeifert04**
Please have a look at the following list and replace the "[ ]" with a "[x]" if
the answer to this question is yes.

- [ ] For new contributors: Did you add yourself to the "Authors.rst" file?

For documentation changes:

- [ ] For documentation changes: Does your commit message include a "[skip ci]"?
      Note that it should not if you changed any examples!

For bugfixes:

- [ ] Did you add an entry to the "Changes.rst" file?
- [ ] Did you add a regression test?
- [ ] Does the commit message include a "Fixes #issue_number" (replace "issue_number").
- [ ] Does this PR add, rename, move or remove any existing functions or parameters?

For new functionality:

- [x] Did you add an entry to the "Changes.rst" file?
- [x] Did you include a meaningful docstring with Parameters, Returns and Examples? **Note: No examples!**
- [x] Does the commit message include a "Fixes #issue_number" (replace "issue_number").
- [x] Did you include tests for the new functionality?
- [ ] Does this PR add, rename, move or remove any existing functions or parameters?

Please note that the last point is not a requirement. It is meant as a check if
the pull request potentially breaks backwards-compatibility.

-----------------------------------------

Fixes #371 

TODO:
- More wrapped functions?
- Make a PR to astropy with the changed support_nddata decorator?

I've copied the `support_nddata` decorator from `astropy.nddata` to make it more general (specify attributes to keep, specify attribute->argument_name mapping.

Also included is a `median_filter` function that simply wraps `scipy.ndimage.median_filter` to test the decorator.

### CODE REVIEW

**Comment by MSeifert04** [comment]
Does anyone know how to fix the two Sphinx issues:

- `<autosummary>:None: WARNING: toctree contains reference to nonexisting document u'api/ccdproc.median_filter'`, maybe because it's only decorated?
- `/home/travis/build/astropy/ccdproc/docs/ccdproc/index.rst:1: WARNING: py:obj reference target not found: scipy.ndimage.filters.median_filter` (it is in that location: https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.ndimage.filters.median_filter.html!)

Also the LTS fails because https://github.com/astropy/astropy/pull/4626 wasn't backported. I'll think about how to fix that.

**Comment by MSeifert04** [comment]
ok, I found out why that Sphinx error happened.

**Comment by MSeifert04** [comment]
I think this is mostly ready now. In retrospect I don't know if it was a good idea to use a modified `support_nddata`. Originally I just wanted it to allow copying attributes from the input to the output but I found so many possible bugs/pitfalls that I think I completly overhauled it.

Maybe using a wrapper function like:

```
def median_filter(data, *args, **kwargs):
    """See `scipy.ndimage.median_filter` for arguments. Enjoy!"""
    if isinstance(data, CCDData):
        out_kwargs = {'meta': data.meta.copy(), 'unit': data.unit}
        result = ndimage.median_filter(data.data, *args, **kwargs)
        return CCDData(result, **out_kwargs)
    else:
        return ndimage.median_filter(data, *args, **kwargs)
```

would have been much easier... 😞

**Comment by mwcraig** [comment]
Would it make sense to move the `support_nddata` changes back to astropy rather than maintaining a separate version here? I think there would be time to get it in for astropy 1.3. Detailed comments coming in a moment.

**Comment by mwcraig** [comment]
Just took a longer look. How about using your [wrapper function idea](https://github.com/astropy/ccdproc/pull/415#issuecomment-257809191) here to get the median_filter in the next ccdproc relationship , and doing a PR on astropy to update `@support_nddata` (an idea which has seen little use in practice I think).

**Pull request closed without merging**
