### PR TITLE
Add .mailmap and update changelog/authors

### PR DESCRIPTION
**Pull request by mwcraig**
Opening a pull request for this mostly to trigger one last round of testing against astropy dev.

### CODE REVIEW

**Comment by bsipocz** [comment]
@mwcraig - You may want to consider to turn on cron testing on travis, once a week tunning the tests on the latest master. You can also use the ``EVENT_TYPE`` env variable in ``.travis.yml`` to control which set of tests to run.

**Comment by MSeifert04** [comment]
What exactly is the `.mailmap`? Does this keep track of mail changes of the gh account?

**Comment by mwcraig** [comment]
@bsipocz -- definitely will. Also going to try actually automating maintenance the conda channels also.

**Comment by mwcraig** [comment]
@MSeifert04 -- it is really only used by `git log` and `git shortlog` to combine contributions made by the same actual person under different names/emails into one consistent name. Completely unnecessary, but I felt like bikeshedding this morning apparently. Actually, its one advantage is that now the names in `git shortlog -s -n` should match the names we have listed in our contributors list.

**Comment by MSeifert04** [comment]
@mwcraig thanks for the explanation. 👍

**Pull request merged**
