### PR TITLE
Adding photoutils as dependency

### PR DESCRIPTION
**Pull request by souravsingh**

### CODE REVIEW

**Comment by souravsingh** [comment]
This PR is related to issue #260 
Do we need to update to docs for this?

**Comment by crawfordsm** [comment]
Thanks for the contribution @souravsingh !   I need to take care of a few other pull requests before this one.  At this time, ccdproc does not require this, but it will in the future so thanks for the PR.   We will also have to update the testing files as well when it does require this so that it is included, so there might be some further comments on this.

**Comment by MSeifert04** [comment]
@souravsingh - Isn't it called``photutils``? You do mean https://photutils.readthedocs.org/en/latest/?

**Comment by souravsingh** [comment]
My Bad! I am sorry for the mistake

**Comment by MSeifert04** [comment]
Thank you @souravsingh but I'm going to close this for now. 

If we really need it as dependency it will be included in the relevant PR. We don't need to add dependencies "just in case".

**Pull request closed without merging**
