### PR TITLE
Ignore wcs

### PR DESCRIPTION
**Pull request by crawfordsm**
For arithmetic between two CCDData objects, this will ignore any difference between WCS unless compare_wcs is set to True

### CODE REVIEW

**Comment by crawfordsm** [comment]
Address #204 and #283 for `ccdproc`

**Comment by MSeifert04** [comment]
I think the naming is quite good since in https://github.com/astropy/astropy/pull/4272 I'll introduce the same parameter. But with a slightly different mechanism. Please also note: https://github.com/astropy/astropy/pull/4503. I think your change will probably be no problem with either of these but better safe than sorry.

**Comment by crawfordsm** [comment]
Thanks @MSeifert04, I did try to follow your naming as that would make future updates hopefully easier.  Unfortunately, I had to do something so that `CCDData` would work with astropy v1.0, otherwise I would have just updated it to use your PRs.   Hopefully this can be depreciated in the not too distant future.

**Comment by mwcraig** [comment]
Looks good, merging. @AnthonyHorton this may be of interest to you.

**Pull request merged**
