### PR TITLE
Catch Exceptions when reading FITS file with malformed header

### PR DESCRIPTION
**Pull request by MSeifert04**
For bugfixes:

- [x] Did you add an entry to the "Changes.rst" file?
- [x] Did you add a regression test?
- [ ] Does the commit message include a "Fixes #issue_number" (replace "issue_number").
- [ ] Does this PR add, rename, move or remove any existing functions or parameters?

See also https://github.com/astropy/astropy/pull/6500

### CODE REVIEW

**Comment by crawfordsm** [comment]
There is a test failure in here related to the test that you created -- is that due to different versions or something needed in the astropy version?

**Comment by MSeifert04** [comment]
One of the failures will go away when https://github.com/astropy/astropy/pull/6489 is merged. The other one should be fine (I restarted the test) because https://github.com/astropy/astropy/pull/6500 has been merged.

It's a bit tricky to sync `ccdproc` with `astropy`. 😄

**Comment by MSeifert04** [comment]
Yes, seems okay. The only failure is unrelated to this PR and can only be fixed upstream (https://github.com/astropy/astropy/pull/6489)

**Comment by bsipocz** [comment]
Well, upstream PR is only waiting for a review, so @crawfordsm if you could have a look, we could merge it rather soon.

**Comment by crawfordsm** [comment]
okay reviewed and merged the other one -- and now this is passing

**Pull request merged**
