### PR TITLE
Create AUTHORS.rst

### PR DESCRIPTION
**Pull request by souravsingh**
Added a file for Contributors of the Project.

### CODE REVIEW

**Comment by crawfordsm** [comment]
Thanks @souravsingh.   I think we will need to do a clean up of the git log as the commits related to astropy-helpers should probably be removed as they are not direct contributions to ccdproc.

**Comment by bsipocz** [comment]
@crawfordsm - I don't think it's necessary to hack the log and rewrite history.

The commits are coming from the ``package-template`` and not from ``astropy-helpers``. Maybe the easiest would be to cross match the commit hashes against the template. The ones that don't match are ccdproc only.

**Comment by bsipocz** [comment]
Also, all commits before 9185b8bb2da61d85db038b19ad41a3e13d51907b seems to be coming from the template.

**Comment by crawfordsm** [comment]
@souravsingh can you implement @bsipocz suggestion and see what the list returns?  All the wording should be updated to reflect this is for ccdproc and not astropy

**Comment by souravsingh** [comment]
@crawfordsm I will get on to it.

**Comment by mwcraig** [comment]
Merging as-is, will open a separate PR in a few minutes to clean up the list.

**Comment by mwcraig** [comment]
Thanks, @souravsingh!

**Comment by souravsingh** [comment]
Thanks for merging the PR @mwcraig

**Comment by MSeifert04** [comment]
@souravsingh - I think you missed the ``@`` when crediting hamogu.

**Pull request merged**
